
// Objective-C API for talking to the following Go packages
//
//	github.com/oneiro-ndev/ndaumath/pkg/keyaddr
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Keyaddr_FRAMEWORK_H__
#define __Keyaddr_FRAMEWORK_H__

#include "Keyaddr.objc.h"
#include "Universe.objc.h"

#endif
