// Objective-C API for talking to github.com/oneiro-ndev/ndaumath/pkg/keyaddr Go package.
//   gobind -lang=objc github.com/oneiro-ndev/ndaumath/pkg/keyaddr
//
// File is generated by gobind. Do not edit.

#ifndef __Keyaddr_H__
#define __Keyaddr_H__

@import Foundation;
#include "Universe.objc.h"


/**
 * WordsFromBytes takes an array of bytes and converts it to a space-separated list of
words that act as a mnemonic. A 16-byte input array will generate a list of 12 words.
 */
FOUNDATION_EXPORT NSString* KeyaddrWordsFromBytes(NSString* lang, NSData* b, NSError** error);

/**
 * WordsToBytes takes a space-separated list of words and generates the set of bytes
from which it was generated (or an error).
 */
FOUNDATION_EXPORT NSData* KeyaddrWordsToBytes(NSString* lang, NSString* w, NSError** error);

#endif
