export const TRANSACTION_TYPES = [
     { id:1,item:"Transfer"},
     { id:2,item:"ChangeValidation"},
     { id:3,item:"ReleaseFromEndowment"},
     { id:4,item: "ChangeRecoursePeriod"},
     { id:5,item: "Delegate"},
     { id:6,item: "CreditEAI"},
     { id:7,item: "Lock"},
     { id:8,item: "Notify"},
     { id:9,item: "SetRewardsDestination"},
     { id:10,item: "SetValidation"},
     { id:11,item: "Stake"},
     { id:12,item: "RegisterNode"},
     { id:13,item: "NominateNodeReward"},
     { id:14,item: "ClaimNodeReward"},
     { id:15,item: "TransferAndLock"},
     { id:16,item: "CommandValidatorChange"},
     { id:17,item:  "UnregisterNode"},
     { id:18,item:  "Unstake"},
     { id:19,item:  "Issue"},
     { id:20,item: "CreateChildAccount"},
     { id:21,item:"RecordPrice"},
     { id:22,item:"SetSysvar"},
     { id:23,item: "SetStakeRules"},
     { id:24,item: "ChangeSchema"},
];