const APP_BACKGROUND_COLOR = '#1c2227';
const DRAWER_BACKGROUND_COLOR = '#414042';
const LINK_ORANGE = '#dea85a';

export default {
  APP_BACKGROUND_COLOR,
  DRAWER_BACKGROUND_COLOR,
  LINK_ORANGE
};
