const APP_BACKGROUND_COLOR = '#1c2227';
const DRAWER_BACKGROUND_COLOR = '#414042';
const LINK_ORANGE = '#dea85a';
const ASTERISKS_RED = '#f75f4b';
const ICON_GRAY = '#A9A9A9';

export default {
  APP_BACKGROUND_COLOR,
  DRAWER_BACKGROUND_COLOR,
  LINK_ORANGE,
  ASTERISKS_RED,
  ICON_GRAY
};
