const LOCALE = 'en-US'
const CURRENT_PRICE_CURRENCY = 'USD'
const NUMBER_OF_KEYS_TO_GRAB_ON_RECOVERY = 50
const NDAU_SUMMARY_PRECISION = 3
const NDAU_DETAIL_PRECISION = 8
const BACKGROUND_TASK_INTERVAL = 300000 // 5 minutes

export default {
  LOCALE,
  CURRENT_PRICE_CURRENCY,
  NUMBER_OF_KEYS_TO_GRAB_ON_RECOVERY,
  NDAU_SUMMARY_PRECISION,
  NDAU_DETAIL_PRECISION,
  BACKGROUND_TASK_INTERVAL
}
