const HARDENED_CHILD_BIP_44 = 44
const ACCOUNT_CREATION_KEY_CHILD = 100
const NDAU_CONSTANT = 20036 // which is 0x4e44 in hex, which are the two letters ND in ASCII
const DERIVED_ROOT_YES = 'yes'
const DERIVED_ROOT_NO = 'no'
const DERIVED_ROOT_UNKNOWN = 'unknown'
const TESTNET_ADDRESS = 'tn'
const MAINNET_ADDRESS = 'nd'
const APP_LANGUAGE = 'en'

const NORMAL_MODE = 'normal'
const PASSWORD_RESET_MODE = 'password-reset'
const GENESIS_MODE = 'genesis'
const NEW_PASSWORD_MODE = 'new-password'

const TEMP_USER = 'temp-user'

const NDAU_EPOCH = '2000-01-01T00:00:00Z'
const QUANTA_PER_UNIT = 100000000
const RATE_DENOMINATOR = QUANTA_PER_UNIT * 10000

export default {
  HARDENED_CHILD_BIP_44,
  ACCOUNT_CREATION_KEY_CHILD,
  NDAU_CONSTANT,
  DERIVED_ROOT_NO,
  DERIVED_ROOT_UNKNOWN,
  DERIVED_ROOT_YES,
  TESTNET_ADDRESS,
  MAINNET_ADDRESS,
  APP_LANGUAGE,
  NORMAL_MODE,
  PASSWORD_RESET_MODE,
  GENESIS_MODE,
  NEW_PASSWORD_MODE,
  TEMP_USER,
  NDAU_EPOCH,
  QUANTA_PER_UNIT,
  RATE_DENOMINATOR
}
